version: '3.8'
services:
  backend-flask:
    environment:
      FRONTEND_URL: "http://${HOSTNAME}:3000"
      BACKEND_URL: "http://${HOSTNAME}:4567"
    image: dnachman/aws-bootcamp-cruddur-2023-backend-flask:latest
    ports:
      - 4567:4567
      
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "http://${HOSTNAME}:4567"
    image: dnachman/aws-bootcamp-cruddur-2023-frontend-react-js
    ports:
      - "3000:3000"

networks:
  internal-network:
    driver: bridge
    name: cruddur
